#!/bin/bash
# Apply /etc/odoo/resources.conf to systemd, Docker Compose, and odoo.conf.
set -euo pipefail

CONF="${ODOO_RESOURCES_CONF:-/etc/odoo/resources.conf}"
ODOO_HOME="${ODOO_HOME:-/opt/odoo}"
ODOO_CONF="${ODOO_CONF:-$ODOO_HOME/odoo.conf}"
COMPOSE_OVERRIDE="${COMPOSE_OVERRIDE:-$ODOO_HOME/docker-compose.override.yml}"
ODOO_DROPIN_DIR=/etc/systemd/system/odoo.service.d
NGINX_DROPIN_DIR=/etc/systemd/system/nginx.service.d

if [[ ! -f "$CONF" ]]; then
  echo "missing $CONF" >&2
  exit 1
fi

# --- INI helpers -----------------------------------------------------------

ini_get() {
  local section="$1" key="$2" file="$3"
  awk -v s="$section" -v k="$key" '
    BEGIN { insec=0 }
    /^\[/ {
      insec = ($0 == "[" s "]")
      next
    }
    insec && $0 ~ /^[[:space:]]*#/ { next }
    insec && $0 ~ /^[[:space:]]*$/ { next }
    insec && index($0, "=") {
      split($0, a, "=")
      key=a[1]
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      if (key == k) {
        val=substr($0, index($0, "=")+1)
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", val)
        print val
        exit
      }
    }
  ' "$file"
}

require_key() {
  local section="$1" key="$2" val
  val="$(ini_get "$section" "$key" "$CONF")"
  if [[ -z "$val" ]]; then
    echo "missing [$section] $key in $CONF" >&2
    exit 1
  fi
  printf '%s' "$val"
}

# Upsert key=value under [options] in odoo.conf (preserve other content).
odoo_conf_set() {
  local key="$1" value="$2" file="$3"
  local tmp
  tmp="$(mktemp)"
  awk -v k="$key" -v v="$value" '
    BEGIN { inopt=0; done=0 }
    /^\[options\]/ { inopt=1; print; next }
    /^\[/ {
      if (inopt && !done) { print k " = " v; done=1 }
      inopt=0
      print
      next
    }
    inopt && $0 ~ ("^[[:space:]]*" k "[[:space:]]*=") {
      print k " = " v
      done=1
      next
    }
    { print }
    END {
      if (!done) {
        if (!inopt) print "[options]"
        print k " = " v
      }
    }
  ' "$file" > "$tmp"
  cat "$tmp" > "$file"
  rm -f "$tmp"
}

# --- Read config -----------------------------------------------------------

ODOO_MEMORY_MAX="$(require_key odoo MemoryMax)"
ODOO_CPU_QUOTA="$(require_key odoo CPUQuota)"
ODOO_TASKS_MAX="$(require_key odoo TasksMax)"
WORKERS="$(require_key odoo workers)"
MAX_CRON="$(require_key odoo max_cron_threads)"
LIM_SOFT="$(require_key odoo limit_memory_soft)"
LIM_HARD="$(require_key odoo limit_memory_hard)"
LIM_CPU="$(require_key odoo limit_time_cpu)"
LIM_REAL="$(require_key odoo limit_time_real)"
LIM_REQ="$(require_key odoo limit_request)"

PG_MEM="$(require_key postgres mem_limit)"
PG_CPUS="$(require_key postgres cpus)"
PG_SHM="$(require_key postgres shm_size)"
PG_SHARED="$(require_key postgres shared_buffers)"
PG_EFF="$(require_key postgres effective_cache_size)"
PG_WORK="$(require_key postgres work_mem)"
PG_MAINT="$(require_key postgres maintenance_work_mem)"
PG_CONN="$(require_key postgres max_connections)"

NGX_MEMORY_MAX="$(require_key nginx MemoryMax)"
NGX_CPU_QUOTA="$(require_key nginx CPUQuota)"
NGX_TASKS_MAX="$(require_key nginx TasksMax)"

# --- systemd drop-ins ------------------------------------------------------

install -d -m 755 "$ODOO_DROPIN_DIR"
cat > "$ODOO_DROPIN_DIR/resources.conf" <<EOF
[Service]
MemoryMax=${ODOO_MEMORY_MAX}
CPUQuota=${ODOO_CPU_QUOTA}
TasksMax=${ODOO_TASKS_MAX}
EOF

if systemctl cat nginx >/dev/null 2>&1; then
  install -d -m 755 "$NGINX_DROPIN_DIR"
  cat > "$NGINX_DROPIN_DIR/resources.conf" <<EOF
[Service]
MemoryMax=${NGX_MEMORY_MAX}
CPUQuota=${NGX_CPU_QUOTA}
TasksMax=${NGX_TASKS_MAX}
EOF
fi

# --- odoo.conf process limits ---------------------------------------------

if [[ ! -f "$ODOO_CONF" ]]; then
  echo "missing $ODOO_CONF" >&2
  exit 1
fi

odoo_conf_set workers "$WORKERS" "$ODOO_CONF"
odoo_conf_set max_cron_threads "$MAX_CRON" "$ODOO_CONF"
odoo_conf_set limit_memory_soft "$LIM_SOFT" "$ODOO_CONF"
odoo_conf_set limit_memory_hard "$LIM_HARD" "$ODOO_CONF"
odoo_conf_set limit_time_cpu "$LIM_CPU" "$ODOO_CONF"
odoo_conf_set limit_time_real "$LIM_REAL" "$ODOO_CONF"
odoo_conf_set limit_request "$LIM_REQ" "$ODOO_CONF"
chown odoo:odoo "$ODOO_CONF" 2>/dev/null || true
chmod 640 "$ODOO_CONF"

# --- Postgres Compose override --------------------------------------------

cat > "$COMPOSE_OVERRIDE" <<EOF
# Generated by odoo-resources.sh from $CONF — do not edit by hand.
services:
  db:
    mem_limit: ${PG_MEM}
    cpus: ${PG_CPUS}
    shm_size: ${PG_SHM}
    command:
      - postgres
      - -c
      - shared_buffers=${PG_SHARED}
      - -c
      - effective_cache_size=${PG_EFF}
      - -c
      - work_mem=${PG_WORK}
      - -c
      - maintenance_work_mem=${PG_MAINT}
      - -c
      - max_connections=${PG_CONN}
EOF
chown odoo:odoo "$COMPOSE_OVERRIDE" 2>/dev/null || true

# --- Nginx websocket upstream (workers>0 → gevent :8072) -----------------

NGINX_SITE="${NGINX_SITE:-/etc/nginx/sites-available/odoo}"
if [[ -f "$NGINX_SITE" ]]; then
  if [[ "$WORKERS" -gt 0 ]]; then
    WS_UPSTREAM=odoo-longpolling
  else
    WS_UPSTREAM=odoo
  fi

  if [[ "$WORKERS" -gt 0 ]] && ! grep -q 'upstream odoo-longpolling' "$NGINX_SITE"; then
    tmp="$(mktemp)"
    awk '
      BEGIN { done=0 }
      /^upstream odoo([[:space:]]|\{)/ { inu=1 }
      inu && /^}/ && !done {
        print
        print "upstream odoo-longpolling {"
        print "    server 127.0.0.1:8072;"
        print "}"
        done=1
        inu=0
        next
      }
      { print }
    ' "$NGINX_SITE" > "$tmp"
    cat "$tmp" > "$NGINX_SITE"
    rm -f "$tmp"
  fi

  sed -i -E \
    -e "/location \\/websocket/,/}/{s|proxy_pass http://odoo(-longpolling)?;|proxy_pass http://${WS_UPSTREAM};|}" \
    -e "/location \\/longpolling/,/}/{s|proxy_pass http://odoo(-longpolling)?;|proxy_pass http://${WS_UPSTREAM};|}" \
    "$NGINX_SITE"

  if [[ "$WORKERS" -gt 0 ]] && ! grep -q 'location /longpolling' "$NGINX_SITE"; then
    tmp="$(mktemp)"
    awk -v up="$WS_UPSTREAM" '
      /location \/websocket/ { inws=1 }
      inws && /^[[:space:]]*}/ {
        print
        print "    location /longpolling {"
        print "        proxy_pass http://" up ";"
        print "    }"
        inws=0
        next
      }
      { print }
    ' "$NGINX_SITE" > "$tmp"
    cat "$tmp" > "$NGINX_SITE"
    rm -f "$tmp"
  fi
fi

# --- Apply ----------------------------------------------------------------

systemctl daemon-reload

if [[ -f "$ODOO_HOME/docker-compose.yml" ]]; then
  (cd "$ODOO_HOME" && docker compose up -d)
fi

systemctl try-restart odoo.service
if systemctl is-enabled nginx >/dev/null 2>&1 || systemctl is-active nginx >/dev/null 2>&1; then
  if nginx -t 2>/dev/null; then
    systemctl reload nginx.service || systemctl try-reload-or-restart nginx.service
  else
    echo "warning: nginx -t failed; left previous config running" >&2
  fi
fi

echo "odoo resources applied:"
echo "  odoo: MemoryMax=${ODOO_MEMORY_MAX} CPUQuota=${ODOO_CPU_QUOTA} workers=${WORKERS}"
echo "  postgres: mem_limit=${PG_MEM} cpus=${PG_CPUS} shared_buffers=${PG_SHARED}"
echo "  nginx: MemoryMax=${NGX_MEMORY_MAX} CPUQuota=${NGX_CPU_QUOTA}"
